client
dev tun
proto udp

# Поменять IP-адрес и порт на соответствующие серверу OpenVPN
remote 172.17.0.2 1194

ca /etc/openvpn/certs/ca.crt
cert /etc/openvpn/certs/client.crt
key /etc/openvpn/certs/client.key

engine bee2evp
dh none

# Можно выбрать другие алгоритмы шифрования
data-ciphers belt-cfb256
cipher belt-cfb256
tls-version-min 1.2
tls-version-max 1.2
tls-cipher DHT-BIGN-WITH-BELT-CTR-MAC-HBELT

auth belt-hash

verb 3