proto udp

dev tun

ca /etc/openvpn/certs/ca.crt
cert /etc/openvpn/certs/server.crt
key /etc/openvpn/certscd/server.key

dh none
engine bee2evp
# Можно выбрать другие адреса
server 10.8.0.0 255.255.255.0

keepalive 10 120

# Можно выбрать другие алгоритмы шифрования
data-ciphers belt-cfb256
cipher belt-cfb256
tls-version-min 1.2
tls-version-max 1.2
tls-cipher DHT-BIGN-WITH-BELT-CTR-MAC-HBELT

auth belt-hash

status openvpn-status.log

verb 3